<!--
  ~ ** Notice of Modification **
  ~
  ~ This file has been altered from its original version by the Cryptomator team.
  ~ For a detailed history of modifications, please refer to the version control log.
  ~
  ~ The original file can be found at https://github.com/googleapis/google-http-java-client
  ~
  ~ ~~
  ~
  ~ https://cryptomator.org/
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.google.http-client</groupId>
    <artifactId>google-http-client-parent</artifactId>
    <version>1.47.1-dev.0001</version><!-- {x-version-update:google-http-client-parent:current} -->
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>google-http-client-android</artifactId>
  <version>1.47.1-dev.0001</version><!-- {x-version-update:google-http-client-android:current} -->
  <name>Fork of com.google.http-client:google-http-client-android for Cryptomator for Android</name>
  <description>
    Unofficial, unaffiliated and unassociated fork of https://github.com/googleapis/google-http-java-client for internal use in Cryptomator for Android.
  </description>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <links>
            <link>http://download.oracle.com/javase/7/docs/api/</link>
          </links>
          <doctitle>${project.name} ${project.version}</doctitle>
          <windowtitle>${project.artifactId} ${project.version}</windowtitle>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>  
            <manifestEntries>
              <Automatic-Module-Name>com.google.api.client.extensions.android</Automatic-Module-Name>
            </manifestEntries>
          </archive> 
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>com.google.http-client</groupId>
      <artifactId>google-http-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.android</groupId>
      <artifactId>android</artifactId>
      <version>4.1.1.4</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
